### ISSUE TITLE
SELECT ServerProperty('Edition') not working

### ISSUE THREAD

**Issue by jacargentina** [tediousjs/tedious#593] opened 2017-06-23 15:19 UTC
Coming from there https://github.com/patriksimek/node-mssql/issues/496 but it seems a tedious bug (or _missing feature_?)

This query just works

```sql
select @@version as Version
```
This doesnt:

```sql
select SERVERPROPERTY('Edition') as Version
```

Can it be fixed/added to the library?

**Comment by v-suhame** [comment] 2017-06-28 17:47
@jacargentina The root cause of failure is, driver isn't properly handling response of type sql_variant with varchar data in it (or in general, data of any variable length type). `SERVERPROPERTY('Edition')` also returns sql_variant. It's fixed in #596.

**Closed** 2017-07-10 23:07 UTC
