### ISSUE TITLE
[FEATURE REQUEST] Export first-party TS declarations

### ISSUE THREAD

**Issue by IlCallo** [tediousjs/tedious#1489] opened 2022-11-02 10:37 UTC
**Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it**
The package cannot be used with first-party TS declarations

**Describe the preferred solution**
The package is written in TS, type declarations should be generated at build time and exposed via `types` property
You should add `tsc --declaration --emitDeclarationOnly` at the end of your build script to use TSC to only generate types  

**Describe alternatives you've considered**
Using outdated `@types/tedious`

**Additional context**
https://github.com/tediousjs/tedious/issues/1067

**Comment by MichaelSun90** [comment] 2022-11-02 16:48
Hi @IlCallo,Thanks for bring this up. Actually I have a [comment ](https://github.com/tediousjs/tedious/issues/1406#issuecomment-1262815707)in another issue explained the cause why we do not have the type declaration release with the project at the first place. We are looking into generate type declaration and replace the outdated one.

**Comment by IlCallo** [comment] 2022-11-02 17:52
Yeah, I got that, I was providing you the solution, check this out: https://github.com/tediousjs/tedious/pull/1490

**Comment by zijchen** [comment] 2024-01-23 23:55
Any update on this? I'm trying to update to v9 and running into errors like `'clientSecret' does not exist in type ConnectionAuthentication`. I sent this PR to fix this in `@types/mssql` too

**Comment by MichaelSun90** [comment] 2024-01-25 17:58
Hi @zijchen,  just to clarify, do you mean v9 of the driver? #1490 still has some failing checks, we will see if we can find time to resolve those and work from there.

**Comment by MichaelSun90** [comment] 2024-03-06 20:48
Since #1490 1490 is merged and release, I think we can close this. If needed, feel free to reopen this one.

**Closed by MichaelSun90** 2024-03-06 20:48 UTC
Labels: feature-request
