### ISSUE TITLE
Support for VarChar UTF-8

### ISSUE THREAD

**Issue by aklietz** [tediousjs/tedious#1143] opened 2020-08-11 16:25 UTC
SQL Server 2019 now supports UTF-8 natively, stored internally as `VarChar(n)` using a collation such as `Latin1_General_100_CI_AS_SC_UTF8`.  (CI = case insensitive, AS = accent sensitive, SC = include supplementary UTF8 characters).  A native UTF-8 database column saves 50% space over `NVarChar` for databases that contain mostly Western European content. It also reduces the TDS network traffic by a similar amount. It's a big win.

I've been trying to coax Tedious to accept VarChar bindings containing UTF-8 strings, but no joy. I found in bug in `mssql` where it was wrongly passing in UTF-8 character lengths using `string.length` when it needed to send byte lengths using `Buffer.byteLength(string, 'utf8')` for `VarChar(n)`, but the UPDATEs were still getting munged at the Tedious level.  Packet tracing shows the UTF-8 2-byte values are getting garbled in weird ways.  For example the copyright symbol © should be encoded as 0xa9 0x0a but the TDS packet trace shows it being sent as 0xa9 0x0e (huh?).  

Furthermore, SQL Server chops out any incoming multibyte UTF-8 characters on UPDATE or INSERT (another bug?).  I'm also wondering if there is a magic 'Use UTF-8' flag that needs to be enabled in the TDS packet protocol for UPDATE and INSERT.  SELECT seems to work okay.

**Comment by IanChokS** [comment] 2020-08-11 17:59
Hi @aklietz 

Thanks for raising this issue. We'll get started to work on UTF-8 support!

**Comment by jeremy-w** [comment] 2021-03-04 14:57
This is a blocker for using tedious (via knex 0.95.0+) for me as well. UTF-8 is as much a default choice for encoding for me as UTC is for timezone.

@aklietz Re: the magic 'Use UTF-8' flag, I don't know about update/insert in particular, but I had a peek at the TDS v30 2020-10-01 doc, and at the session-establishment level, the LOGIN7 stream indeed has a UTF8_SUPPORT FeatureEx introduced in TDS 7.4. The collation rules used in COLMETADATA also have an fUTF8 flag.

**Comment by jeremy-w** [comment] 2021-07-27 12:12
@IanChokS I'm not clear on how Tedious tracks the column collation for writing data even absent UTF-8 support. Does it currently not, and that's worked because most folks are using NVARCHAR exclusively?

I see when parsing values, the Metadata is used to drive codepage selection, with a default encoding of utf8 when codepage is not available.

When sending requests, it looks like varchars are always encoded as ascii, unless the parameter value was provided directly as a Buffer.

There's a vague hint in the TDS standard that tracking the current DB would let one track the relevant collation for encoding. This comes in discussing LOGIN7, where it notes that if the DB change flag is _not_ set, then "the client will be unaware of any accompanying collation changes." This makes it sound like tracking the current DB would be needed in order to respect the expected default collation when sending collated column data. But AFAICT, a Tedious connection does not presently track this. When it comes to changes in database, collation, or charset communicated by an ENVCHANGE packet, it looks like the connection re-emits the database+charset event and drops the collation change event, without modifying any internal connection state as is done with the transaction-related events.

In light of that, and the scant coverage of encoding handling in the TDS docs, the "sending data" part definitely seems the trickier. I haven't yet snooped on a protocol session between a reference implementation ("What is Azure Data Studio up to?") to see how various flavors of collation config affect its behavior, and the way it manages sending data appropriate for each column based on the input data.

**Comment by jeremy-w** [comment] 2021-07-27 12:21
From my investigation so far (reading docs and spelunking tedious code), it looks like a first shot would look like:

- send fUTF8 feature flag in LOGIN7
- if FEATUREEXTACK for fUTF8 received and positive, save that in connection state.
- use that utf8 state to change the default encoding for varchar string values we send: default to encoding varchar strings as utf8, rather than ascii. continue to leave varchar buffers alone.
- decoding: detect a utf8 collation, and clear any charset in the column metadata, so the "decode as utf-8 absent charset" behavior Just Works. or handle a utf8 charset, if one is sent.

I'd want to buttress this with an end-to-end integration test that selects data, inserts data, and updates data as a start. Bulk data and TVP handling would be addressed later.

**Comment by jeremy-w** [comment] 2021-07-27 12:23
@aklietz Do you have a ready to run code snippet reproducing your problems?

It looks like © should encode as c2 a9. The ascii flattening Tedious is doing for varchar string params drops the c2 and gives just a9, which shows up as the replacement character when I print it. It looks like providing the param value as a Buffer rather than a string would be a workaround if you're using Tedious directly.

**Comment by IanChok** [comment] 2021-07-27 15:58
Sorry, I'm actually not too sure. 

@arthurschreiber I think you'd have a more better understanding of this issue.

**Comment by arthurschreiber** [comment] 2021-07-28 08:00
@jeremy-w 👋 

You're absolutely right, `varchar` and `char` data types are pretty broken right now, and will require a bit of work to make them behave correctly. Adding UTF-8 support should be pretty straightforward once the fundamental issues have been worked out.

I've been looking into the required changes as well recently, because having collation support work correctly is a pre-requisite to continue our work on the "Always Encrypted" feature as well (/cc @MichaelSun90).

> * send fUTF8 feature flag in LOGIN7
> * if FEATUREEXTACK for fUTF8 received and positive, save that in connection state.
> * use that utf8 state to change the default encoding for varchar string values we send: default to encoding varchar strings as utf8, rather than ascii. continue to leave varchar buffers alone.
> * decoding: detect a utf8 collation, and clear any charset in the column metadata, so the "decode as utf-8 absent charset" behavior Just Works. or handle a utf8 charset, if one is sent.

I'm not sure this is quite right, but I've not looked deeply into UTF-8 implementation details as well. On the receiving side, UTF8 works like any other collation, i.e. we only decode values using UTF-8 if the server tells us that the value is utf-8 via the collation information that is send back.

Only on the sending side, if the user explicitly specifies a collation, we need to check whether the server acknowledged the UTF-8 collation feature flag. If the server told us during a database change that the collation of the database is utf-8, we don't need to care about the feature flag, I think.

Anyway, if you want to take a stab at implementing this, I'm happy to help and review. If you don't feel like working on this, it is somewhere on my list of things that I'd like to work on in the future. 😬

**Comment by jeremy-w** [comment] 2021-07-28 12:21
I wish the TDS spec had more to say on collations and text encoding. The verbiage around the UTF-8 feature is odd; it makes it sound like the server won't send the client any UTF-8 data unless it's active, either, though I've no clue how that would work in practice if the column's data is in a UTF-8 encoding to begin with. Perhaps it's a backwards way of making UTF-8 support effectively obligatory for newer clients. The specific verbiage I'm staring at is:

> Failure of the client to receive an acknowledgement of UTF-8 feature extension support from the server indicates that the server cannot send or receive UTF-8 encoded data. (from the FeatureExt table near the end of the long LOGIN7 section)

with the "cannot send" part being what's extra odd here.

**Comment by jeremy-w** [comment] 2021-07-28 12:49
i think an initial "enable utf-8, fall back to utf-8 instead of ascii" approach to getting utf-8 varchar working will not conflict with the work on Always Encrypted in https://github.com/tediousjs/tedious/pull/1020 and likely not with the "set param collation" work in https://github.com/tediousjs/tedious/pull/1140. that latter looks especially important to getting collations working properly through-and-through. i'd like to proceed with that.

do you find that reverse engineering sql server behavior and how it plays out in TDS is quite usual in this project? the TDS spec is awfully low on semantic detail; it seems very mono-focused on the wire format. is there another spec for those higher-level "how a SQL Server client cooperates with a SQL Server server" details i should review?

**Comment by jeremy-w** [comment] 2021-08-31 01:00
i believe this is fixed as of tedious@12.2.0 between the changes of: 

- [v12.1.0](https://github.com/tediousjs/tedious/releases/tag/v12.1.0) for varchar & collation support  #1318
- [v12.2.0](https://github.com/tediousjs/tedious/releases/tag/v12.2.0) for UTF-8 support #1317

(and various preceding to fix the collations list and bulk-load support)

**Closed** 2021-08-31 06:03 UTC
Labels: feature-request
