### ISSUE TITLE
RequestError: Error converting data type decimal to decimal.

### ISSUE THREAD

**Issue by eelti** [tediousjs/tedious#869] opened 2019-02-17 02:08 UTC
RequestError: Error converting data type decimal to decimal.
    at RequestError (C:\vue\qOmeter\node_modules\tedious\lib\errors.js:32:12)
    at Parser.tokenStreamParser.on.token (C:\vue\qOmeter\node_modules\tedious\lib\connection.js:723:34)
    at Parser.emit (events.js:189:13)
    at Parser.parser.on.token (C:\vue\qOmeter\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
    at Parser.emit (events.js:189:13)
    at addChunk (C:\vue\qOmeter\node_modules\readable-stream\lib\_stream_readable.js:296:12)
    at readableAddChunk (C:\vue\qOmeter\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (C:\vue\qOmeter\node_modules\readable-stream\lib\_stream_readable.js:239:10)
    at Parser.Transform.push (C:\vue\qOmeter\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at doneParsing (C:\vue\qOmeter\node_modules\tedious\lib\token\stream-parser.js:80:14)
  message: 'Error converting data type decimal to decimal.',
  code: 'EREQUEST',
  number: 8114,
  state: 2,
  class: 16,

My nodeJs code:
`

> var Connection = require('tedious').Connection;
> 
> var config ={
>     server: 'xx.xx.xx.xx',
>     authentication:{
>         type: 'default',
>         options:{
>             userName: 'xxxx',
>             password: 'xxxx',
>         }
>     }
> };
> 
> var connection = new Connection(config);
> 
> connection.on('connect', function(err) {
>         // If no error, then good to go...
>         executeProcedure();
>     }
> );
> var Request = require('tedious').Request;
> var TYPES = require('tedious').TYPES;
> 
> function executeProcedure(){
>     var request = new Request('wg.zwg.Q_OMETER_DATA_OP',
>         function(err){
>             if (err){
>                 console.log(err);
>             }
>             //connection.close();
>         });
>     request.addOutputParameter('TPP_Q_CTN_LAST', TYPES.Decimal);
>     request.addOutputParameter('TPP_QTY_WALL_LAST',TYPES.Decimal);
>     request.addOutputParameter('TPP_Q_CTN_CURRENT',TYPES.Decimal);
>     request.addOutputParameter('TPP_QTY_WALL_CURRENT',TYPES.Decimal);
>     request.addOutputParameter('TPP_Q_CTN_RATE',TYPES.Decimal);
>     request.addOutputParameter('TPP_QTY_WALL_RATE',TYPES.Decimal);
>     request.addOutputParameter('WBI_Q_CTN_LAST',TYPES.Decimal);
>     request.addOutputParameter('WBI_QTY_WALL_LAST',TYPES.Decimal);
>     request.addOutputParameter('WBI_Q_CTN_CURRENT',TYPES.Decimal);
>     request.addOutputParameter('WBI_QTY_WALL_CURRENT',TYPES.Decimal);
>     request.addOutputParameter('WBI_Q_CTN_RATE',TYPES.Decimal);
>     request.addOutputParameter('WBI_QTY_WALL_RATE',TYPES.Decimal);
> 
>     request.on('returnValue', function (paramName, value, metadata) {
>         console.log(paramName + ' :  ' + value);
>     });
> 
>     connection.callProcedure(request);
> }

`

If I use TYPES.Int or TYPES.NVarChar is working fine but I really want use decimal(10,4)

my Ms Sql procedure is 
`

> CREATE  or ALTER  PROCEDURE [zwg].[Q_OMETER_DATA_OP]
> 	@TPP_Q_CTN_LAST			decimal(10,4) OUT,
> 	@TPP_QTY_WALL_LAST		decimal(10,4) OUT,
> 	@TPP_Q_CTN_CURRENT		decimal(10,4) OUT,
> 	@TPP_QTY_WALL_CURRENT	decimal(10,4) OUT,
> 	@TPP_Q_CTN_RATE			decimal(10,4) OUT,
> 	@TPP_QTY_WALL_RATE		decimal(10,4) OUT,
> 	@WBI_Q_CTN_LAST			decimal(10,4) OUT,
> 	@WBI_QTY_WALL_LAST		decimal(10,4) OUT,
> 	@WBI_Q_CTN_CURRENT		decimal(10,4) OUT,
> 	@WBI_QTY_WALL_CURRENT	decimal(10,4) OUT,
> 	@WBI_Q_CTN_RATE			decimal(10,4) OUT,
> 	@WBI_QTY_WALL_RATE		decimal(10,4) OUT
> AS
> BEGIN
> 	SET NOCOUNT ON;
> 
> Big query....
> 
> 	SELECT @TPP_Q_CTN_LAST = cast(SUM(qc4.TPP_Q_CTN_LAST) as decimal(10, 4)),
> 				 @TPP_QTY_WALL_LAST = cast(SUM(qc4.TPP_QTY_WALL_LAST) as decimal(10, 4)),
> 				 @TPP_Q_CTN_CURRENT = cast(SUM(qc4.TPP_Q_CTN_CURRENT) as decimal(10, 4)),
> 				 @TPP_QTY_WALL_CURRENT = cast(SUM(qc4.TPP_QTY_WALL_CURRENT) as decimal(10, 4)),
> 				 @TPP_Q_CTN_RATE = cast(SUM(qc4.TPP_Q_CTN_RATE) as decimal(10, 4)),
> 				 @TPP_QTY_WALL_RATE = cast(SUM(qc4.TPP_QTY_WALL_RATE) as decimal(10, 4)),
> 				 @WBI_Q_CTN_LAST = cast(SUM(qc4.WBI_Q_CTN_LAST) as decimal(10, 4)),
> 				 @WBI_QTY_WALL_LAST = cast(SUM(qc4.WBI_QTY_WALL_LAST) as decimal(10, 4)),
> 				 @WBI_Q_CTN_CURRENT = cast(SUM(qc4.WBI_Q_CTN_CURRENT) as decimal(10, 4)),
> 				 @WBI_QTY_WALL_CURRENT = cast(SUM(qc4.WBI_QTY_WALL_CURRENT) as decimal(10, 4)),
> 				 @WBI_Q_CTN_RATE = cast(SUM(qc4.WBI_Q_CTN_RATE) as decimal(10, 4)),
> 				 @WBI_QTY_WALL_RATE = cast(SUM(qc4.WBI_QTY_WALL_RATE) as decimal(10, 4))
> 	FROM qc4;
> 
> END
> go

`

**Comment by MichaelSun90** [comment] 2019-02-27 18:46
Hi @eelti, sorry that we take a while to get back to yo. I have looked into this issue, and I am able to reproduce on my side. I think it is caused by the decimal precision and scale setting does not match on both side.  You can try to set the precision and scale on Node Js side to specifically make the precision and scale to 10 and 4.  
eg: 
var option =  {"precision":10,"scale":4}
request.addOutputParameter('TPP_Q_CTN_LAST', TYPES.Decimal,<value that you want put here>,option);

There is a link from Tedious document which explains the parameters, hope this helps. 
http://tediousjs.github.io/tedious/api-request.html#function_addOutputParameter

**Comment by MichaelSun90** [comment] 2019-03-25 18:37
Hi @eelti, is the precision and scale settings help you with the issue? Or, it is still reporting the error after you set them?

**Comment by leblancmeneses** [comment] 2019-04-16 00:40
@MichaelSun90  Options fixed my issue.  Thank you!

```
message: 'Arithmetic overflow error converting numeric to data type numeric.',
code: 'EREQUEST',
number: 8115,
state: 8,
class: 16,
```

  request.addParameter('latitude', TYPES.Decimal, data.latitude || null, {precision:9,scale:6});
  request.addParameter('longitude', TYPES.Decimal, data.longitude || null, {precision:9,scale:6});

**Comment by saketnimbargi** [comment] 2019-12-06 05:10
> Hi @eelti, is the precision and scale settings help you with the issue? Or, it is still reporting the error after you set them?

Hi @MichaelSun90 I'm also facing a similar issue, I tried your solution but that not working. Is there any other work around? Thanks.

**Comment by MichaelSun90** [comment] 2019-12-06 17:54
HI @saketnimbargi,  Can you provide a simple repo script for your issue, so I can try on my side? Also, what tedious and node version are you currently using?

**Comment by saketnimbargi** [comment] 2019-12-07 18:02
I'm using Tedious: **v6.2.0**  and Node: **v10.15.3**


Error:
  message: 'Error converting data type decimal to decimal.',
  code: 'EREQUEST',
  number: 8114,
  state: 2,
  class: 16,


config.js
`exports.dbconfig = {
  server:'xx.xx.xx.xx',
  authentication: {
    type:'default',
    options: {
      userName:'xxxx',
      password:'xxxx',
    }
  },
  options: {
    database:'xxxxx',
    useColumnNames:true,
    rowCollectionOnDone:true,
  },
}`

`function storesSP(serialNo, amount){
 const getProc = new Request('SPName', function(err, rowCount){
      if(err){
        console.log(err);
      }
    });
  getProc.addParameter('Pacno', TYPES.BigInt, serialNo);
  getProc.addParameter('Pbal', TYPES.Decimal, amount, { precision: 15, scale: 2 });

 getProc.addOutputParameter('XRValue', TYPES.Decimal);
 getProc.on('returnValue', function(paramaterName, value) {
  cosole.log(value);
 })
}`

**Comment by saketnimbargi** [comment] 2019-12-09 08:29
Hi @eelti  I was able to get the desired output after doing some trail and error. I got the desired output after specifying the **value** argument in the 
`request.addOutputParameter(name,` type, [value], [options])`

Can you help me understand why do I need to specify the **value**? This doesn't happen when I call other stored procedures which have an output paramater.

**Comment by MichaelSun90** [comment] 2019-12-09 18:09
Hi @saketnimbargi, if you want to include an "options" parameter, the current behavior is that you have to put a "value" in the parameter list since the parameter is read sequentially. If you put in a "options" without a "value" like this: request.addOutputParameter(name, type,[options]), the "options" will be read as the "value" and cause some issue.  
For the other stored procedures with output parameter, do you have "options" within the addOutputParameter function call or you only called it as "addOutputParameter(name, type)"?

**Comment by saketnimbargi** [comment] 2019-12-10 03:19
For the other stored procedures, I haven't used the "options" parameter within the addOutputParameter function call I've called it as "addOutputParameter(name, type)" and it has worked.

**Comment by MichaelSun90** [comment] 2019-12-10 17:41
Hi @saketnimbargi, That is what I am trying to explain in the previous message. The parameters for addOutputParameter are read sequentially. Therefore, if you only call it with the first two parameters - "name" and "type", this should be fine. When it comes to the moment, the function tries to read "values" and  "options", which does  not appear in the function call, the undefined values will be assigned to options and values within the function. However, if the function is called with parameters like this: addOutputParameter(name, type, options), this will cause a problem. Since the function is actually expected a "value" as the third parameter, but it gets an "options" instead. Then, the function still trying to use the "options" as a "value", which going to causing problems for sure.

**Comment by saketnimbargi** [comment] 2019-12-11 06:25
@MichaelSun90 I got it. Thanks a lot. :+1:

**Comment by IanChokS** [comment] 2019-12-13 19:47
@eelti, does @MichaelSun90 solution solve your issue as well? If not feel free to re-open this issue.

**Closed by IanChokS** 2019-12-13 19:47 UTC
