### ISSUE TITLE
Connection lost - Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by irgijs** [tediousjs/tedious#903] opened 2019-05-24 14:31 UTC
Since tedious version 2.7.0 the following error event is emitted. This error is still emitted in the newest release (v6.1.1):

`Connection lost - Cannot call write after a stream was destroyed`

We tested this with both SQL Server 2016 and 2017. We are still trying to reproduce the error and we will report back if we found something.

**Comment by irgijs** [comment] 2019-05-27 08:27
Additional information:
- I found the specific commit which introduces the error: https://github.com/tediousjs/tedious/commit/908488ad8641eda34d3a7a9be74631490d2f1184
- We use the [tedious connection pool](https://github.com/tediousjs/tedious-connection-pool) (modified in fork in such a way that tedious is used as peer dependency)

**Comment by arthurschreiber** [comment] 2019-05-27 09:14
@irgijs There's a bunch of connection lifecycle issues in current _and_ older `tedious` releases, plus the connection pool code does not handle lifecycle issues well either. 😞 

I did some work that was targeted at improving the situation over at https://github.com/tediousjs/tedious/compare/arthur/rework-connection-close, but I never finished turning it into a proper PR. Seeing the issues you're running into makes me think I should revive that branch and finish the work there. 🙇 

Would you mind also sharing the modifications you made to the connection pool code? 😬

**Comment by irgijs** [comment] 2019-05-27 09:50
@arthurschreiber We only changed the package.json file to so that it would accept any tedious release (as peer dependency):
```
{
	"name": "tedious-connection-pool",
	"version": "1.0.0",
	"description": "Connection Pool for tedious.",
	"main": "lib/connection-pool.js",
	"scripts": {
		"test": "node_modules/.bin/mocha --expose-gc test/test.js"
	},
	"repository": {
		"type": "git",
		"url": "https://bitbucket.org/irefact/tedious-connection-pool.git"
	},
	"keywords": [
		"tedious",
		"connection",
		"pool"
	],
	"author": {
		"name": "Ben Page",
		"email": "ben.page@openreign.com"
	},
	"contributors": [
		{
			"name": "Ben Page",
			"email": "ben.page@openreign.com"
		},
		{
			"name": "Mike D Pilsbury",
			"email": "mike.pilsbury@gmail.com"
		}
	],
	"license": "MIT",
	"peerDependencies": {
		"tedious": ">= 1.0.0"
	},
	"devDependencies": {
		"mocha": "^3.0.2",
		"simple-statistics": "^2.1.0"
	}
}
```

**Comment by kevinkevp** [comment] 2019-05-28 21:41
Try with this in the config:
options.encrypt: false

Works for me, in a local MSSQL

**Comment by arthurschreiber** [comment] 2019-06-01 13:56
@kevinkevp That will probably work because that will disable the TLS stream that is used for encryption purposes, greatly simplifying the internal connection handling. But it's not a proper fix, because encryption support is a hard requirement for many use cases.

I'll take https://github.com/tediousjs/tedious/compare/arthur/rework-connection-close and see if I can polish it up!

**Comment by dhollenbeck** [comment] 2019-06-14 17:06
I am getting the same error as the @irgijs and therefore unable to update the tedious driver.

**Comment by irgijs** [comment] 2019-06-17 08:41
@arthurschreiber Are you expecting to find a solution anytime soon? Is there something we can do to help you?

**Comment by irgijs** [comment] 2019-07-26 08:08
@arthurschreiber We really want to update to the latest tedious version, but this issue prevents us from doing so. How can we help you to fix this problem?

**Comment by ErikJansenIRefact** [comment] 2019-08-12 17:19
@arthurschreiber This open issue is blocking our way forward. We do need a more recent Tedious version but are depending on stream processing as well. You mentioned finishing https://github.com/tediousjs/tedious/compare/arthur/rework-connection-close. Can you give us an idea of when this might be expected?

**Comment by irgijs** [comment] 2019-08-22 10:02
We have identified the culprit. It is caused by the connection pool, see https://github.com/tediousjs/tedious-connection-pool/issues/58

**Comment by IanChokS** [comment] 2019-12-13 18:01
@irgijs @ErikJansenIRefact, since this issue looks like it's due to `tedious-connection-pool`, i'll close the issue here for now. If you think there's a cause due to Tedious itself related to this, feel free to re-open this issue.

**Closed by IanChokS** 2019-12-13 18:01 UTC

**Comment by mastodon0** [comment] 2020-04-16 11:34
This issue is not only restricted to `tedious-conection-pool`

You get the same error if you use `options.encrypt: true` on Node v12+ with old SQL Server versions. This is caused by Node v12 requiring TLS 1.2. 
There is nothing tedious could do about it, so you got 3 options:
* install the [TLS 1.2 security patch](https://support.microsoft.com/en-us/help/3135244/tls-1-2-support-for-microsoft-sql-server) for your SQL Server
* run node with backwards compatibility flag: `node --tls-min-v1.0`
* disable encrypted communication by setting `options.encrypt: false`

**Comment by arthurschreiber** [comment] 2020-04-16 15:18
@mastodon0 You can also specify an earlier TLS version to use just for the connection opened by tedious. See https://github.com/tediousjs/tedious/issues/914#issuecomment-517011077

**Comment by arthurschreiber** [comment] 2020-04-16 15:29
I'm wondering if we could improve the messaging around this issue, to make it clearer to users what the issue is and how this can be worked around (and what the implications of those workarounds are).
