### ISSUE TITLE
Getting empty Array

### ISSUE THREAD

**Issue by jopep100** [tediousjs/tedious#824] opened 2018-11-16 11:52 UTC
Hey there, I try to get into Tedious and nodejs. This is my code, but why is the Array empty and why is it shown before the sql statement?

```
var Connection = require('tedious').Connection;
var Request = require('tedious').Request;
var config = {
    userName: '*******',
    password: '*****',
    server: '*******',
    // If you are on Microsoft Azure, you need this:
    options: {encrypt: true, database: '********',rowCollectionOnRequestCompletion:true,rowCollectionOnDone: true}
};
const connection = new Connection(config);
var data = [];

connection.on('connect', function(err) {
    // If no error, then good to go...
        console.log("connected");
        console.log('Reading rows from the Table...');
        // Read all rows from table
        request = new Request(
            "SELECT * from dbo.LeistungskundeAccount",
            function(err, rowCount, rows)
            {
                console.log(rowCount + ' row(s) returned');
            }
        );

        request.on('row', function(columns) {
            columns.forEach(function(column) {
                data.push(column.value);
                console.log("%s\t%s", column.metadata.colName, column.value);});
        });
        connection.execSql(request);
    }
);

console.log(data);

```

**Comment by Hadis-Fard** [comment] 2018-11-17 02:18
@jopep100 the reason lies in the async nature of Node, `console.log(data)` gets executed before the connection events fire off. In order to make  data available you can use callbacks to access the data after the values are pushed into the data array, for example the code below would print out the data,

``` js
createConnection((data)=>{
    console.log(data);
});

function createConnection(cb){
    const connection = new Connection(config);
    
    connection.on('connect', function(err) {
        // If no error, then good to go...
            console.log("connected");
            console.log('Reading rows from the Table...');
            // Read all rows from table
            request = new Request( "SELECT * from myTable", function(err, rowCount, rows){
                    console.log(rowCount + ' row(s) returned');});
    
            request.on('row', function(columns) {
                var data = [];
                columns.forEach(function(column) {
                    
                    data.push(column.value);
                   // console.log("%s\t%s", column.metadata.colName, column.value);
                });
                // data is available here
                cb(data);
            });
            connection.execSql(request);
    });
}
```

**Comment by Hadis-Fard** [comment] 2018-11-19 22:45
closing this assuming the problem is resolved , feel free to re-open the issue if otherwise

**Closed** 2018-11-19 22:45 UTC

**Comment by jopep100** [comment] 2018-11-20 08:38
It helped a little bit, but i am not able to use it by my self.
I want to get SQL Data from my Server with Tedious and send it to my html page,probably with an array. (Or what do you think is the best solution ?) Can you just give me a example how it works. Or is there a good video tutorial ?

**Comment by Hadis-Fard** [comment] 2018-11-20 19:01
The code above would get the data back into the array using callback , depending on you application you may want to use Node promises or async/await for a better performance instead of callbacks  :bowtie:. There are many js front end frameworks to send it to the html, choosing one depends on your application and is out of the scope of this repository
