### ISSUE TITLE
ConnectionError: Failed to connect to <server name> in 15000ms

### ISSUE THREAD

**Issue by aniltomar10** [tediousjs/tedious#833] opened 2018-11-26 16:55 UTC
I am using tedious-connection-pool. I am getting this error intermittently.
unhandledRejection: ConnectionError: Failed to connect to in 15000ms

**Comment by Hadis-Fard** [comment] 2018-11-26 21:53
@aniltomar10 Could you send a repo?

**Comment by Hadis-Fard** [comment] 2018-11-29 19:08
@aniltomar10 this seems to be the issue with[ tediousjs/node-mssql ](https://github.com/tediousjs/node-mssql/)

**Comment by aniltomar10** [comment] 2018-11-30 23:30
@Hadis-Fard I had copied wrong stack trace. 
Also I found that tedious-connection-pool is using old version of tedious dependency. This issue was there in tedious package but later it was fixed. As tedious-connection-pool is still using older version of tedious package, issue is there.
Now I have replaced tedious-connection-pool in my project with node-mssql. I hope this should fix the issue.

**Comment by Hadis-Fard** [comment] 2018-12-03 19:22
@aniltomar10 glad to hear you figured it out, I close the issue , feel free to reopen it if you encounter it again

**Closed by Hadis-Fard** 2018-12-03 19:22 UTC

**Comment by aniltomar10** [comment] 2018-12-04 18:37
@Hadis-Fard looks like it didn't fix the issue. I received same error today. Both tedious-connection-pool and mssql throwing same error.

**Comment by LIMRoss** [comment] 2018-12-21 15:12
I'm seeing the same issue (mssql 4.30, tedious 2.7.1). The connection pool is notified of the error events just fine, and behaves as expected if the server isn't available on the initial connection. The problem is any errors after the pool is created seems to be emitting the correct error message, but is an unhandled rejection, so no errors bubble up that way, and throws NodeJS into a tizzy.

**Comment by LIMRoss** [comment] 2018-12-21 16:02
@aniltomar10  I noticed by bouncing around similar issues that passing acquireTimeoutMillis in your config.pool will still give you the unhandled rejection, but will at least pass an error back through your code's callback\promises
