### ISSUE TITLE
Some datatypes (like NULL) crash the process

### ISSUE THREAD

**Issue by PatrLind** [tediousjs/tedious#321] opened 2015-10-08 08:39 UTC
I have not had time to really dig into this, but this is what I experience at the moment.

When I do SQL queries with bound parameters that are containing a null value I get a crash in request.js line 153. The error seems to be that some data types (like NULL) doesn't have a validate function available.

I'm using version 1.12.3
This is the function:

``` javascript
Request.prototype.validateParameters = function () {
    var i, len, parameter, ref, value;
    ref = this.parameters;
    for (i = 0, len = ref.length; i < len; i++) {
      parameter = ref[i];
      value = parameter.type.validate(parameter.value); // <---- ERROR HERE
      if (value instanceof TypeError) {
        return this.error = new RequestError("Validation failed for parameter '" + parameter.name + "'. " + value.message, "EPARAM");
      }
      parameter.value = value;
    }
    return null;
  };
```

**Comment by arthurschreiber** [comment] 2015-10-08 09:16
Can you post the complete error + backtrace?

**Comment by Ramzeus** [comment] 2015-10-08 09:23
I hope this is what you want:
```
c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\node_modules\tedious\lib\request.js:154
      value = parameter.type.validate(parameter.value);
                             ^
TypeError: undefined is not a function
    at Request.validateParameters (c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\node_modules\tedious\lib\request.js:154:30)
    at Request.transformIntoExecuteSqlRpc (c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\node_modules\tedious\lib\request.js:90:14)
    at Connection.execSql (c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\node_modules\tedious\lib\connection.js:962:13)
    at _execNextInQueue (c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\index.js:578:11)
    at process._tickCallback (node.js:355:11)
```

The parameter variable was containing this:
```
{ type: { type: 'NULL', name: 'Null', id: 31 },
  name: 'p2',
  value: null,
  output: false,
  length: undefined,
  precision: undefined,
  scale: undefined }
```

**Comment by arthurschreiber** [comment] 2015-10-08 09:25
How did you assign this parameter to the request? There's something wrong with tedious here, but a reproducible test case would help me a long way.

**Comment by Ramzeus** [comment] 2015-10-08 09:38
I'm using a library called any-db-mssql (that I had to do some local modifications to).
The library is adding the parameter as this:
```javascript 
request.addParameter(keys[i], type, value, options);
```

Where the function parameters are:
```javascript
console.log('addParameter', keys[i], type, value, options);

// Output:
addParameter p2 { type: 'NULL', name: 'Null', id: 31 } null null
```

A working type seems to look more like this:
```javascript
addParameter p1 { type: 'NVARCHAR',
  name: 'NVarChar',
  hasCollation: true,
  dataLengthLength: 2,
  maximumLength: 4000,
  declaration: [Function],
  resolveLength: [Function],
  writeTypeInfo: [Function],
  writeParameterData: [Function],
  validate: [Function],
  id: 231 } value null
```

Maybe this is  an error in the calling library that is triggering wrong behavior?

**Comment by arthurschreiber** [comment] 2015-10-08 09:54
Weird. I don't think `tedious` currently accounts for people using `tedious.TYPES.Null` as a parameter type. I'll dig into this once I find some free time!

**Comment by Ramzeus** [comment] 2015-10-08 09:55
Ok, thanks :+1: 
If you know of an alternative way of setting a NULL value please feel free to inform me :)

**Comment by arthurschreiber** [comment] 2015-10-08 09:57
> If you know of an alternative way of setting a NULL value please feel free to inform me :)

You can just use the actual type that the parameter would have if it's not null, and then pass null as the actual value.

**Comment by v-suhame** [comment] 2018-07-25 23:09
@arthurschreiber @Hadis-Fard  I think we should deprecate `TYPES.Null` too. Since `NULL` not a SQL Server data type, the `sp_executesql` query formed with null as type will run into syntax error (in Server side).

plus, from TDS spec,
> NULLTYPE can be sent to SQL Server (for example, in RPCRequest), but SQL Server never emits NULLTYPE data.

What do you think?

**Closed** 2018-07-27 05:32 UTC
