### ISSUE TITLE
Tedious does not accept 01/01/1900 as date input

### ISSUE THREAD

**Issue by boris-marinov** [tediousjs/tedious#621] opened 2017-10-06 11:00 UTC
When I give tedious the date  01/01/1900 (for example from data which was previously extracted from an SQL table) it gives an error.

![image](https://user-images.githubusercontent.com/4872512/31275031-44d632a8-aa9e-11e7-9e98-a5a6d866af33.png)

I think that this should be equivalent to giving an invalid date.

**Comment by chdh** [comment] 2017-10-06 19:23
The problem is that your database field is SmallDateTime, Tedious Options.useUTC is true (the default) and your value is two hours before 01/01/1900.

`console.log( new Date("Mon Jan 01 1900 00:00:00 GMT+0200").toUTCString() );`
==> Sun, 31 Dec 1899 22:00:00 GMT

**Comment by arthurschreiber** [comment] 2017-10-19 19:08
@chdh seems to be spot on, so I'll go ahead and close this. 😄

**Closed by arthurschreiber** 2017-10-19 19:08 UTC
