### ISSUE TITLE
 Sequelize with MS SQL using tedious getting two same arrays in result.

### ISSUE THREAD

**Issue by rahulkulmi** [tediousjs/tedious#688] opened 2018-01-22 05:47 UTC
I am using "tedious": "2.2.3" and "sequelize": "4.31.2" and call stored procedures.
Then i will getting response in array and inside that array i am getting two same array instant one array. So please fix this problem as soon as possible.

Here is the sample response

```
"responseData": [
        [
            {
                "id": 1,
                "username": "rahul",
                "password": 12345,
                "phone": 1234,
                "createdAt": "2018-01-19T11:54:51.642Z",
                "updatedAt": "2018-01-19T11:54:51.642Z"
            }
        ],
        [
            {
                "id": 1,
                "username": "rahul",
                "password": 12345,
                "phone": 1234,
                "createdAt": "2018-01-19T11:54:51.642Z",
                "updatedAt": "2018-01-19T11:54:51.642Z"
            }
        ]
    ]
```

**Comment by v-suhame** [comment] 2018-01-22 18:11
@rahulkulmi Can you share more details, so we can look into this issue? What is the DDL of stored procedure? What is the query/TSQL that `sequelize` sends? Are you able to directly reproduce it in `tedious` (without using `sequelize` )? It would be super helpful to track, if you can share a repo code based on `tedious`.

**Comment by rahulkulmi** [comment] 2018-01-23 03:51
@v-suhame  Thanks for quick reply
This is my stored procedures code for MS SQL database

```
CREATE PROCEDURE myuser
AS
BEGIN
  SELECT * FROM users where username='rahul';
END
```
And this is my sequelize code used inside the Node Express app.
```
sequelize.query("EXEC myuser;", { type: sequelize.QueryTypes.RAW})
    .then(function(summary) {
     return callback(null, summary);
    })

OR

sequelize.query('myuser').then(function (response) {
      return callback(null, response);
    }).catch(function (err) {
      return callback(err);
    });
```

**Comment by v-suhame** [comment] 2018-01-23 21:01
Looks like `sequelize` is processing the data sent by `tedious` before returning it to the user. 

This issue is not from tedious because, the format of data returned by tedious is quiet different than the one posted above(to start with tedious data has metadata info). The query you are using is a simple one that has been tested several times with tedious, I dint notice any repetition of row when querying directly using `tedious`.

Please raise this issue in `sequelize` :)

**Comment by arthurschreiber** [comment] 2018-01-23 21:28
Hey @rahulkulmi,

I'm sorry to hear you're running into trouble with tedious. Unfortunately, as @v-suhame already pointed out, there is nothing we can do here to help you, unless you have a reproducible case for this issue that uses plain tedious, without sequelize on top. I hope you understand that we can't really help you out with issues that might stem from libraries other than tedious here. 😞

You probably want to open an issue over at https://github.com/sequelize/sequelize/issues or ask on stackoverflow instead.

I'll close this issue for now. If you can reproduce the same faulty behaviour with plain tedious, feel free to reopen this issue!

**Closed by arthurschreiber** 2018-01-23 21:28 UTC

**Comment by rahulkulmi** [comment] 2018-01-24 03:56
@v-suhame and @arthurschreiber 
Thanks for reply.
