### ISSUE TITLE
encoding Varchar NVarchar problem with Azure DataWarehause(Synapse)

### ISSUE THREAD

**Issue by ElMurte** [tediousjs/tedious#1313] opened 2021-08-05 21:25 UTC
this problem still persist with tedious driver 11.0.7 and mssql 7.13 on Azure Datawerehause(Synapse) when using BULK INSERT ( the isssue comes when `await request.bulk.table(mytable)` is called ) a screenshot of the error
![image](https://user-images.githubusercontent.com/64850733/128409282-22668b0c-490c-44a8-b47f-1c1f47159c37.png).
I had tried to update the driver dependency and mssql to latest version but seems the problem persist.
The problem comes because the encoding for Varchar and NVarchar is not working as it should be. The BULK works if i use Integers and Dates(only)... i think this pull request https://github.com/tediousjs/tedious/pull/1295 is correleted to the error but i'm not sure

_Originally posted by @ElMurte in https://github.com/tediousjs/node-mssql/issues/1033#issuecomment-893818214_

**Comment by arthurschreiber** [comment] 2021-08-07 10:59
I believe this will be fixed by https://github.com/tediousjs/tedious/pull/1314.

**Comment by arthurschreiber** [comment] 2021-08-07 11:00
Also, I think this is a duplicate of #392.

**Comment by arthurschreiber** [comment] 2021-08-31 16:56
Can you try this again with `v12.2.0`? I think this issue should be fixed now.

**Comment by ElMurte** [comment] 2021-08-31 20:07
> Can you try this again with `v12.2.0`? I think this issue should be fixed now.

i cannot have access to the repository no more since i was doing an internship, btw i will notify them.

**Comment by arthurschreiber** [comment] 2021-09-09 17:57
Okay. I will close this then. 🙇‍♂️ If you or anyone notices that this is still not working correctly, please let us know!

**Closed by arthurschreiber** 2021-09-09 17:57 UTC
