### ISSUE TITLE
Bulkload to Temporary Table Error 

### ISSUE THREAD

**Issue by codethyme** [tediousjs/tedious#1005] opened 2019-11-16 18:43 UTC
Having an issue then trying to bulkload to a temporary table:

**Temp Table Creation Script:** 

```js
CREATE TABLE ##DummyTable_Site ( [DimId] int NOT NULL, [Type] nvarchar(200), [Status] nvarchar(200), [Grp] nvarchar(200), [Cat] nvarchar(200), [Desc] nvarchar(500), [Name] nvarchar(200), [Cd] nvarchar(200) NOT NULL,[CRD] datetime2, [CUId] int, [DSId] int)

connection.newBulkLoad('##DummyTable_Site', { keepNulls: true }, ... );
... Columns and Rows added here
connection.execBulkLoad(bulkLoad);
```
After executing execBulkLoad getting the below error

 **Error**:
message:"An unknown error has occurred. This is likely because the schema of the BulkLoad does not match the schema of the table you are attempting to insert into."

**Comment by mikalai-sokarau** [comment] 2019-11-18 09:44
+1, when I try to update an existing table with an additional column, I get the same error. Any ideas how to fix it? Didn't find anything in the documentation 😔

**Comment by IanChokS** [comment] 2019-11-18 17:41
@mikalai-sokarau Is the table you're trying to update a temp table as well?

**Comment by MichaelSun90** [comment] 2019-11-18 18:24
Hi @mikalai-sokarau, I just went over the doc briefly and found that it actually mentioned that the schema for add columns should match the original table's schema. That may actually be the cause of your error?  http://tediousjs.github.io/tedious/bulk-load.html#function_addColumn

**Comment by mikalai-sokarau** [comment] 2019-11-19 07:11
Hi, guys, thank you for your answers and link to the doc!
Indeed, I found out that schemas are different 😳 
Is it possible to dynamically change the table schema (add one more column) with tedious API?
Or maybe someone can suggest a standard approach to do this manipulation?

**Comment by IanChokS** [comment] 2019-11-19 17:31
You can try just using a regular SQL command such as 
```sql
ALTER TABLE table_name
ADD column_name datatype;
```
Then using the regular tedious API `connection.exec('sqlcommand');`

**Comment by mikalai-sokarau** [comment] 2019-11-28 18:44
Hi @IanChokS, thank you very much, it helped!

**Comment by IanChokS** [comment] 2019-12-13 17:39
@codethyme Does the above solution work for you also? Closing this for now.

**Closed by IanChokS** 2019-12-13 17:39 UTC
Labels: Idle
