### ISSUE TITLE
App Service user-assigned MSI authentication

### ISSUE THREAD

**Issue by sharonchoong** [tediousjs/tedious#1146] opened 2020-08-21 20:51 UTC
Hello, I'm having issues making App Service MSI authentication work. I went through [this tutorial](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi) to set up a user-assigned managed identity.  But I still can't make it work. 

The authentication part of my tedious config is 
```
type: 'azure-active-directory-msi-app-service',
options: {
            clientId: client_ID_of_the_user_assigned_MSI
        } 
```
The error I'm getting at runtime is:
```
ConnectionError: Security token could not be authenticated or authorized.
     at ConnectionError (/home/site/wwwroot/node_modules/tedious/lib/errors.js:13:12)
     at /home/site/wwwroot/node_modules/tedious/lib/connection.js:2843:61
     at getTokenFromCredentials (/home/site/wwwroot/node_modules/tedious/lib/connection.js:2809:24)
     at /home/site/wwwroot/node_modules/@azure/ms-rest-nodeauth/dist/lib/login.js:645:24
     at /home/site/wwwroot/node_modules/@azure/ms-rest-js/dist/msRest.node.js:363:13
     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
   code: 'EFEDAUTH'
 }
```

I saw that @azure/ms-rest-nodeauth is being deprecated for @azure/identity. Could that be why it's not working?

**Comment by IanChokS** [comment] 2020-08-25 16:12
Hi @sharonchoong I'll take a look!

**Comment by IanChokS** [comment] 2020-08-27 21:59
Actually it looks like there's a bug with with @azure/ms-rest-nodeauth https://github.com/Azure/ms-rest-nodeauth/issues/102
I'll check if using @azure/identity will be able to authenticate using MSI

**Comment by sharonchoong** [comment] 2020-08-30 19:19
@IanChokS, appreciate it!  Thanks for looking into this, at least I know where the problem likely is. I can use `azure-active-directory-password` in the meantime, but it doesn't seem to be the recommended way to authenticate based on the Microsoft tutorials.  

Regarding @azure/identity, I think this [pull request](https://github.com/tediousjs/tedious/pull/939) is related.

**Comment by IanChokS** [comment] 2020-08-30 19:21
No problem, I've confirmed that User-Assigned MSI authentication works with the @azure/identity library so I'll try to get that fixed merged ASAP

**Comment by ramya-rao-a** [comment] 2020-09-21 05:03
Hello,

I am from the team that owns the `@azure/ms-rest-nodeauth` package. 

Can someone share details on how https://github.com/Azure/ms-rest-nodeauth/issues/102 is related here as linked a few comments above?
The expectation is that one would call and await on `getToken()` after getting a credential object from the `@azure/ms-rest-nodeauth` package.

**Comment by ramya-rao-a** [comment] 2020-09-21 05:08
If the issue is around user assigned managed identity, then the most recent update to the `@azure/ms-rest-nodeauth` package has a fix for it. Relevant parts from the [changelog](https://github.com/Azure/ms-rest-nodeauth/blob/master/Changelog.md):

> Added support for passing a `clientId` property in the `options` parameter of the MSI based login method `loginWithAppServiceMSI()`. This is required to allow user-assigned managed identities to be used to authenticate through Azure App Services and Azure Functions.

Looking at https://github.com/tediousjs/tedious/pull/939 which is also linked from this PR, it looks like this project is using v2 of the `@azure/ms-rest-nodeauth` package. Updating to the latest v3 should give you the above fix. Please give that a try

**Comment by IanChokS** [comment] 2020-09-21 14:28
@ramya-rao-a Thank you for pointing out that the new version 3 has the fix for user-assigned msi auth 🙇 ! I wasn't aware that the there was a fix in the latest version.  Using the latest version, I was able to successfully access SQL DB from an Azure App Service using user-assigned MSI Auth, so I'll create a PR for Tedious to update the config for `loginWithAppServiceMSI` function. 

Also, according to [this comment](https://github.com/Azure/ms-rest-nodeauth/pull/75#issuecomment-519198541), is your team planning on deprecating `@azure/ms-rest-nodeauth` in favour of `@azure/identity` sometime in the future?

**Comment by IanChokS** [comment] 2020-09-21 14:45
@ramya-rao-a Thank you for pointing out that the new version 3 has the fix for user-assigned msi auth 🙇 ! I wasn't aware that the there was a fix in the latest version.  Using the latest version, I was able to successfully access SQL DB from an Azure App Service using user-assigned MSI Auth, so I'll create a PR for Tedious to update the config for `loginWithAppServiceMSI` function. 

Note: In the function config, I had to also specify `resource` field alongside `clientId` for it to work, but the current documentation specifies only needing `clientId` (for user-assigned). So I'm not sure if `resource` field is required for all use cases, or just mine. 

Also, according to [this comment](https://github.com/Azure/ms-rest-nodeauth/pull/75#issuecomment-519198541), is your team planning on deprecating `@azure/ms-rest-nodeauth` in favour of `@azure/identity` sometime in the future?

**Comment by IanChokS** [comment] 2020-09-21 15:03
@sharonchoong Can you check if PR #1155 will fix your issue? Hopefully all goes well 🤞

**Comment by ramya-rao-a** [comment] 2020-09-21 16:57
> In the function config, I had to also specify resource field alongside clientId for it to work, but the current documentation specifies only needing clientId (for user-assigned). So I'm not sure if resource field is required for all use cases, or just mine.

That is interesting. I am not familiar with the inner details here for quick answer. If you can log an issue in the ms-rest-nodeauth repo with details on your set up (preferably outside of tediousjs :)), then we can take a deeper look and update the docs as needed

>  is your team planning on deprecating @azure/ms-rest-nodeauth in favour of @azure/identity sometime in the future?

Yes, but the progress is slow at the moment. For now, `@azure/ms-rest-nodeauth` is supported and will take bug fixes, but we will not be adding any new features.

**Comment by sharonchoong** [comment] 2020-10-11 23:54
> @sharonchoong Can you check if PR #1155 will fix your issue? Hopefully all goes well

@IanChokS That worked!  Sorry for the delay, I had some trouble rebuilding the module with your PR changes, but the user-assigned MSI authentication worked nicely in the end.  Would be great if this can be merged into master!

**Closed** 2021-02-11 22:30 UTC
